#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-index4.ceda.ac.uk - 2020/06/03 07:14:31
# Search URL: http://esgf-index4.ceda.ac.uk/esg-search/wget/?distrib=false&dataset_id=CMIP6.HighResMIP.ECMWF.ECMWF-IFS-HR.hist-1950.r1i1p1f1.Amon.prw.gr.v20170915|esgf-data3.ceda.ac.uk
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='http://esgf-index4.ceda.ac.uk/esg-search/wget/?distrib=false&dataset_id=CMIP6.HighResMIP.ECMWF.ECMWF-IFS-HR.hist-1950.r1i1p1f1.Amon.prw.gr.v20170915|esgf-data3.ceda.ac.uk'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195001-195012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195001-195012.nc' 'SHA256' 'a846510899d96a2562c8f6bf4ad1ab72ddab30a5e5e38cac868346165ad4c29d'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195101-195112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195101-195112.nc' 'SHA256' '9bf011a53f48d5d48006820a76098a32173e77966e20751c6509ec3c048275a4'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195201-195212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195201-195212.nc' 'SHA256' 'ad5d1dca0407119b65a9c40dcc6d75e0c4e09c6a3dfb92566e3df26a2d66b305'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195301-195312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195301-195312.nc' 'SHA256' '1c7028a650ba863c770a80289ec34aebef2c98a3b6405d6c7efd2929e584e710'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195401-195412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195401-195412.nc' 'SHA256' 'a8ad84299ca46c236a66746e11937d24ffab37ec11c9625abee482c732ff7e7e'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195501-195512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195501-195512.nc' 'SHA256' 'c4dbfceba636233b11902d566ca1f987861be9ff9309bba9836519b564d84818'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195601-195612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195601-195612.nc' 'SHA256' '02126a41d5828242c5a8ebac2d2af2c2880065b9f5d42398eeb78718de94a843'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195701-195712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195701-195712.nc' 'SHA256' 'b659e3c5743d40ec2901dba06a2befa6753e1be12e54e00f9de813c48fdc473b'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195801-195812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195801-195812.nc' 'SHA256' '999584bb03f6c8b5359e04239186576237bf35ec06e4d0aafdd59fbde25ab3e0'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195901-195912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195901-195912.nc' 'SHA256' 'f07a86dfc74bcdd4a231c64e1e4419359d318ca79b8b7931292ab526646a6311'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196001-196012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196001-196012.nc' 'SHA256' 'de8c2d34aea90beea348eaffccc93e0cb7946d8bf5e9d064b1628c7caebead92'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196101-196112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196101-196112.nc' 'SHA256' '6ae634a766613f31586e6ce5933cf04e9c85e07970dced196bfc0352b04d86c1'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196201-196212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196201-196212.nc' 'SHA256' 'b1ad3cf1db86b21d0a506e88b85aa55223516ff0881a453e4ba70957d1c1cdd6'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196301-196312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196301-196312.nc' 'SHA256' '1450ccb7f80fd3c33f51bcd2829d5fdb7401b32421b73a87103d6a87eadcf510'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196401-196412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196401-196412.nc' 'SHA256' 'a1408d62d0d2fc0a3e5a82fae88f3a20c088edc7e0e813705e4ec2db00ef26a8'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196501-196512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196501-196512.nc' 'SHA256' '1729396df75b3574e93098863f4f4416497a498f07dc041af3c4842980e35e3d'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196601-196612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196601-196612.nc' 'SHA256' '2d15145debd0d8c12538ef49ff8fbcc89c9f7a23f4107d55349db9f63ce84af7'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196701-196712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196701-196712.nc' 'SHA256' 'ab5b027c128e217a60cc357808a49faf92180405fba5065f35f28a797fb1ddc0'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196801-196812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196801-196812.nc' 'SHA256' '3d2f1da81c81ee7505502303104e8aa491ed5d03d4a140db25ccc9322baddb9e'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196901-196912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196901-196912.nc' 'SHA256' '35871e63d4e9157c30b79ee3ab1172c265360caf4dda0f1e0ded51d0aa60aca1'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197001-197012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197001-197012.nc' 'SHA256' '0c16a38bee3bcfa9a30384f38c40b593f55c36140ad625693b54ef561d7a9422'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197101-197112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197101-197112.nc' 'SHA256' '7f924fe5eef43c77ebfc24a38d3428d7b729d6135ea201a9f7910abbd50ad4c4'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197201-197212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197201-197212.nc' 'SHA256' 'adedb79c3180aae37276a98d16c743bec1dbc7aba0ba9ff85d2637d52133cc74'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197301-197312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197301-197312.nc' 'SHA256' '35f377c13936261e44284179b4ee7b777e85e601f2ab01e647302d687b611252'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197401-197412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197401-197412.nc' 'SHA256' '77444e8a02b9651a351fdc246e3927e824639204137015d6b96addbd862c90df'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197501-197512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197501-197512.nc' 'SHA256' '16fca1976430e496e27665e26ce954dc659edd43f3a50b7e3dda06c8c9a554ba'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197601-197612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197601-197612.nc' 'SHA256' 'f7e110a550e2552c7c0cf80b4f4f36ce8dca47e81e16274d59c1f77c3c0715c2'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197701-197712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197701-197712.nc' 'SHA256' '141141bf6fe7a5e92a7e084fa2c38d81bc1f80f0469a9d0d2a5de4784f3a09f0'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197801-197812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197801-197812.nc' 'SHA256' '08e3c550a8bf59a49f4b5e40c2c3766cf6ca6435febcb059827145112524c01f'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197901-197912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197901-197912.nc' 'SHA256' '15222ca794a3abcb94b136e3998f63d48db62eb7ad874f54a19e507d16d1b4a1'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198001-198012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198001-198012.nc' 'SHA256' '35713cf0e61c322326109e8bb8719e6f628aa824e9174bf237a56cc59a2cdba5'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198101-198112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198101-198112.nc' 'SHA256' '3259c32e1cf76f562d9a785a166c93462c5e87cfa93360753a82317945e06fe0'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198201-198212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198201-198212.nc' 'SHA256' '5f36a49c0231570b82c4a78fe66bbd22c10ce07fff687410ab01c51e15e7d18a'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198301-198312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198301-198312.nc' 'SHA256' '7c73ce71fe077a61550d977ab899c00d4de7ccbc9fcede10253b8cd1a6648455'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198401-198412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198401-198412.nc' 'SHA256' '6d93d05b0f7b355a0ce7230c1ad798320a62e8cb1176bbb55ffc76a307adc29a'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198501-198512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198501-198512.nc' 'SHA256' '59df556ae152d9328a72b90f556b00e55239a00ab9b9f435c2921c06b4b47833'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198601-198612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198601-198612.nc' 'SHA256' '22d2f37194d342aa548b1b074601b9202a56799a0bbd87a290737c3392116b5c'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198701-198712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198701-198712.nc' 'SHA256' '4f465d5a9807430349ca1a10bc817aa5e1affdfa5467163faa76cdb274c4f8c8'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198801-198812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198801-198812.nc' 'SHA256' 'db029180025c61737bcebf665c28cdcc3d0e4bff9d9713c3534e91068c71aa5c'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198901-198912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198901-198912.nc' 'SHA256' '0c1f95bea0e3f17fe586d27960d68d97ba3f737e00295cba1bf89eea3287d9b8'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199001-199012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199001-199012.nc' 'SHA256' 'ee52408d8b906f266d77585fe8bbd97e0d8390f91f225cca9496def619b28667'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199101-199112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199101-199112.nc' 'SHA256' 'ecd4cd50a0821ef71b722419c3a87dd932dcd123feff8e4ee4725760b9413ac9'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199201-199212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199201-199212.nc' 'SHA256' 'f1e61d39b2d14a6b8649fb58c790c80b6a97b49bb549e10e097020bc3bb23ed3'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199301-199312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199301-199312.nc' 'SHA256' '85f50c1cdc21cb5d5e59f66cb736037802c1ffd2b63bc743b0ef187b2eef7247'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199401-199412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199401-199412.nc' 'SHA256' '65d69787815fcd418bf3988ebba41df4729681f3e80cfa0363fa62740a5fc878'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199501-199512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199501-199512.nc' 'SHA256' 'c8901b9b0d80c24df710edf0ad39e3545963e6998ccfb61e1b37357b7ac1abe6'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199601-199612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199601-199612.nc' 'SHA256' '710b3d289b2a5fca8bd21f7fe0692f5428f9540d5d080d21095e25a202040337'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199701-199712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199701-199712.nc' 'SHA256' 'ce65b3c4457cd44d22d0c9752e6db65f81c592fcdf7b97f70f9bf0c66acc6ee3'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199801-199812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199801-199812.nc' 'SHA256' '877595492b97c6699c442951984942bb2705f348ac87c6703a0c5105e2a6e9e6'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199901-199912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199901-199912.nc' 'SHA256' 'bf7e921b526d6dc964d244a993187415a0c0a646b386edaa015d94e55186bc39'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200001-200012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200001-200012.nc' 'SHA256' 'c004df88b23e65b28306ed8d4233f1ffbfe4ca57541c5b42452b681cc023ad7c'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200101-200112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200101-200112.nc' 'SHA256' '35c9e3e6ea78fae2aea561d807684b440eecc3e3a18dbec837cb84312e825e2e'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200201-200212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200201-200212.nc' 'SHA256' '87cce37a977f2963d96368e1f678fcf40aaf3c54bf9d0b58d9e0eb47c830235d'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200301-200312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200301-200312.nc' 'SHA256' '01da0036bca548e653f875455d1eba59a69a57918060d72d7ad03b3634f8315c'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200401-200412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200401-200412.nc' 'SHA256' '6d40d000e062aa139530b6058fa062744e4cc436da741ffcdea7b2fdee7ce995'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200501-200512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200501-200512.nc' 'SHA256' 'd262ce2f5c78fb64cf2fe280c8a91eb4673acb4e7e099f0a2d3eeeb47dfd22bf'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200601-200612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200601-200612.nc' 'SHA256' '1238dbc9b0ffa508f427c1e023772b7644ed0939fca0e5efeb977cfbc0490b28'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200701-200712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200701-200712.nc' 'SHA256' '508d256a1e7680db6ca8f836869a65ba1f61393096e16f0ec44e22a765e520f8'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200801-200812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200801-200812.nc' 'SHA256' '9eaed66319ac7cb4a2e8333ab369730943d0ce1fe5e7b95ba3a140529039e9b9'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200901-200912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200901-200912.nc' 'SHA256' '4715783019ac7b27281a9603fd904a2e94b0f31d9e880168198a7919b9edd970'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_201001-201012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_201001-201012.nc' 'SHA256' 'dd1ec880040a0d0e0d02bb874676881757d58b43d19544f0442aced2c44b660b'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_201101-201112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_201101-201112.nc' 'SHA256' 'c2543619ba993a794cec4e9b13aff237c5f824ef06180e4dffd0311f2608bbc6'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_201201-201212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_201201-201212.nc' 'SHA256' '45296a77a4c2ca5a312626e34136b924fdb1e712a2d1af6f65061f135fa53279'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_201301-201312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_201301-201312.nc' 'SHA256' 'b1cdc66776a9810d2d99260a75324afb080f44b5cbb32e9c445b8d4c824ac526'
'prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_201401-201412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/prw/gr/v20170915/prw_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_201401-201412.nc' 'SHA256' '8cd780438be405d0a4ba2a250337a4406a05f799772cb1869e9ea40f41959b26'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if ((mVer<5)); then
        echo "Java version 1.5+ is required for retrieving the certificate." >&2
        echo "Current version seems older: $(java -version | head -n1) " >&2  
        return 1
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 65 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
