#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-index4.ceda.ac.uk - 2020/06/03 07:15:16
# Search URL: http://esgf-index4.ceda.ac.uk/esg-search/wget/?distrib=false&dataset_id=CMIP6.HighResMIP.ECMWF.ECMWF-IFS-HR.highresSST-present.r1i1p1f1.Amon.hus.gr.v20170915|esgf-data3.ceda.ac.uk
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='http://esgf-index4.ceda.ac.uk/esg-search/wget/?distrib=false&dataset_id=CMIP6.HighResMIP.ECMWF.ECMWF-IFS-HR.highresSST-present.r1i1p1f1.Amon.hus.gr.v20170915|esgf-data3.ceda.ac.uk'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_195001-195012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_195001-195012.nc' 'SHA256' '46a5abeb01dbf509a9f5bd055b39a3091d73eecc4c4e754b3937b922352e7c29'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_195101-195112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_195101-195112.nc' 'SHA256' '3d88dc6263b8aaf59af4202736b9d6682a7347264c4ce8dba32bbbe10ff24c31'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_195201-195212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_195201-195212.nc' 'SHA256' 'f14a27cfbee669627e31152e4dc86ffd495fc45da7498c37006ebfe7139cdf54'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_195301-195312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_195301-195312.nc' 'SHA256' '71f6e1749e8be094cfbe2e52ab53c2cdba2fcc5b78627fd6e63b2d3957ce1075'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_195401-195412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_195401-195412.nc' 'SHA256' 'dd08ef0494b232524444b9796227de92dc7ad9412168ad3228ac30fed0bc0ad5'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_195501-195512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_195501-195512.nc' 'SHA256' 'ea8d96227b982e3c9dc81cc5c44624bf50c95879c151188e31400ca60ecb06ad'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_195601-195612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_195601-195612.nc' 'SHA256' '6931b90317c5cf09e6039048f662fd44b806c815ef99f486f0608ed78a629450'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_195701-195712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_195701-195712.nc' 'SHA256' 'bf1e1f94cc27f2eee3d8112eecc69ad17a7a364f52fc20990db6300fba8d9c0f'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_195801-195812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_195801-195812.nc' 'SHA256' '078a4bb6ae66a747d3df05af3295a0053d698b41707129ff385113d2a80489a2'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_195901-195912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_195901-195912.nc' 'SHA256' 'f2805f3356a4fcf352257fa32cfa3fe0f5a4a8a1c5467a51348a22d34793d732'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_196001-196012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_196001-196012.nc' 'SHA256' '08bd5f9ca00bccceba380dafc927e4ca63a44fc8d34a7bae21c5d77ee1fe9e5e'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_196101-196112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_196101-196112.nc' 'SHA256' '18e14b8311dc090ab126bfde5e693ba969d3fa201fe46fa504c6bedce1e82f4f'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_196201-196212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_196201-196212.nc' 'SHA256' '46a25b45f99c3161ce98093cc2103f6c41184f2fa97a7902a30cbb8131883179'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_196301-196312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_196301-196312.nc' 'SHA256' '282c119c0f6d8d8466d11977ffe666b06ee9cf4044458b3f654e11440b02e92a'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_196401-196412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_196401-196412.nc' 'SHA256' 'b7147612eb45bee44684fa0fd87991a9f35bc00cebe6373a25e0ba0026f472ba'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_196501-196512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_196501-196512.nc' 'SHA256' '57b96354af28d7f8f6a5f8f82b74c2315865053890bf1eff01868bda6d8b21ba'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_196601-196612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_196601-196612.nc' 'SHA256' '53e4b98b398d2670ac49b28cdf8dc6040843a4386683cbb33757dbb73e02c6b6'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_196701-196712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_196701-196712.nc' 'SHA256' '89ad6ffd6125c8db5486f23f383f8e5061422bc070247f235fd9e9db31bf4266'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_196801-196812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_196801-196812.nc' 'SHA256' 'aa0d900522ca7e26263946a6ea1f418cf116d407706cd048b706cf00a31ddd57'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_196901-196912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_196901-196912.nc' 'SHA256' '67d4beb038b2f26aedfb22e6297e36bad944722e2aa9ecb9ac3d818a52a79396'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_197001-197012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_197001-197012.nc' 'SHA256' 'eeef1e03c6f1e1d3f73933fddfbbb6d88b207f7272a2f4648aa7170956b4b24f'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_197101-197112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_197101-197112.nc' 'SHA256' '619b1d6c5d5e42dc83ab2afcc88d9610726fccad87c44d017f47bf9ef7bad4d0'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_197201-197212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_197201-197212.nc' 'SHA256' 'd8be7080a7fa771a31f69525aa0fcedaa5e8d853fc01bf82692f1d3febd6b0fb'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_197301-197312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_197301-197312.nc' 'SHA256' '343400a37a1a71fdced90f4d27c9525ad6c137f0aa2f6764553fd5a4fba19cca'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_197401-197412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_197401-197412.nc' 'SHA256' 'c0ee3d1d89ce65ee4b05b483516b7452f0c78595cc12e9af1693a2ccc27b43d2'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_197501-197512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_197501-197512.nc' 'SHA256' '231a38a7b4bf2fcf21366109762d43288beaff8a44b1aa48d405b702c005bc53'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_197601-197612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_197601-197612.nc' 'SHA256' 'aa05eb353b0f423ffc0a3bb15310b2a5c202518901706ec3e2aae953217296aa'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_197701-197712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_197701-197712.nc' 'SHA256' 'b382b48b59f7f73e2be7dd25c43ce2ad2da7f97ce0ce7cc725a306b5450069e1'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_197801-197812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_197801-197812.nc' 'SHA256' '912d2f89c2a93684c9756f0e3e18e11d6fff80e73da0072e94dae54181a545c5'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_197901-197912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_197901-197912.nc' 'SHA256' '952f54cfaee21be33f9399dfdd3ae2ed52a95fe50b0da4e1ac1d57df451d9703'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_198001-198012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_198001-198012.nc' 'SHA256' '37b40f3c50906f47fd45cd184543bfeab9752d2c9eeb2816113289936266b485'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_198101-198112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_198101-198112.nc' 'SHA256' '1dfc5978d4cbc9af8ba603141f0c867c2815bfa919354c55ac147dc7e138a9c0'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_198201-198212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_198201-198212.nc' 'SHA256' 'f3c7ff67a8a95e651d3bc62f87e176679d25f44141fa5d0a12fdbf77d19f271b'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_198301-198312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_198301-198312.nc' 'SHA256' '39a681295e03d326c18794f97a45b84b567da28ffd4de0f770b0b66a71d6b3a0'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_198401-198412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_198401-198412.nc' 'SHA256' 'f717458285751fa21a7c213e50b9e3be1ebd22cf9dc5bc644168b33832b4550b'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_198501-198512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_198501-198512.nc' 'SHA256' '25ceb1bf72aa73da6d723a74e2fdec1e8bf56205b279acfd8fc3e1b824794b4c'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_198601-198612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_198601-198612.nc' 'SHA256' '8bf8f478d6d7b350cd8bff42361a965db5110fb6008e791be6e6538d80a9e0eb'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_198701-198712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_198701-198712.nc' 'SHA256' 'afb71fefe4265d78c96fef9844c398109259ebdba3b687b3bcc36746ad78ff0e'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_198801-198812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_198801-198812.nc' 'SHA256' '314457c96d87b104766f064fa3701ee6e9401c05076802c437697bcf4898a8fb'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_198901-198912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_198901-198912.nc' 'SHA256' '68dc91c00c1dfba59a46fabfe5d2d56ca0840ef64b15a2fab223215180525516'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_199001-199012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_199001-199012.nc' 'SHA256' 'b597813551bbf248edecb731ee2fdf807ee8f369e2a6af8b6390ff63119a0390'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_199101-199112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_199101-199112.nc' 'SHA256' '3c56e6dd6390478248cd630a71241af8fcdfc2d428d9ce74ff2a87b02e8bee1e'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_199201-199212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_199201-199212.nc' 'SHA256' '96f34708ac2acee4207b88446766bb30928c3d91d641a2aef22aa3aa3ca8cedd'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_199301-199312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_199301-199312.nc' 'SHA256' '148b86ada5f5d20d5cb1ba618bf32684ea2365330d91169d758f7f6c3a15c80f'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_199401-199412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_199401-199412.nc' 'SHA256' '385024b90e75e07fc131910b4c8b445d8ca29bf0bc196a08a321b5e807838205'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_199501-199512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_199501-199512.nc' 'SHA256' '8ea69d4a6262045d7414577a9ac10ed82f8fca178bb23a4f04a6c99d5016a896'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_199601-199612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_199601-199612.nc' 'SHA256' '6d041fcdb7e941975f1a0e5384dc3cca840771a79ac1275f8e907662be868cce'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_199701-199712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_199701-199712.nc' 'SHA256' '7d9bf05769b2cd640d4b0d86787af52fa43c7321c9d8772022b5dc727f0ae1f6'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_199801-199812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_199801-199812.nc' 'SHA256' 'b97a2a5cc0201fa87eca506d2c59ce5c41a130f31096e45d4ea501f5f4156367'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_199901-199912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_199901-199912.nc' 'SHA256' '7205b5e3984452e81302076daf6d8432bf84556f88a36b6f7d9e16037935710f'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_200001-200012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_200001-200012.nc' 'SHA256' 'a8dfa32b01990e0881700d0e959c250d1fde544877dd24c99a05c28137c183fa'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_200101-200112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_200101-200112.nc' 'SHA256' '897f0654b17d2e97d1d55201295bb3f94014f198adbb6d226a8359259420749a'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_200201-200212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_200201-200212.nc' 'SHA256' '30ab0a4261420b5fcc03bbd677b25f33386f71879503735568465ad00df2f3f2'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_200301-200312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_200301-200312.nc' 'SHA256' '32b29c271c68d7329de4638ed67f18361ffd08555b4d761531f89a56888db457'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_200401-200412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_200401-200412.nc' 'SHA256' '96abadc19105970ec88d4a4c55fd01591f2f8f75cc3c3eaace6fd93fd4ecbace'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_200501-200512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_200501-200512.nc' 'SHA256' '526f3868f3c2702577a07f046d4ff714ce35e85f5e129a1d18bdc490e884670f'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_200601-200612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_200601-200612.nc' 'SHA256' 'd8872e4703167d52b01be5c83f69f70c86e9f4bd368cee68220b8b00822fed59'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_200701-200712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_200701-200712.nc' 'SHA256' 'b579bce39d599a356cd1bc6c0f5638a78fa0e5a6e6d5e3ad14bc31c20c7944b8'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_200801-200812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_200801-200812.nc' 'SHA256' '615bf6a075c737cef254ec4c8257f97c9cbcc16a3bc30e81df5155da816be8ae'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_200901-200912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_200901-200912.nc' 'SHA256' 'e201813a4ebd0433f5bf8fa6df12841f0b0e4c3968cc71f27a6dd57aaea1a832'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_201001-201012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_201001-201012.nc' 'SHA256' 'a9af0d5d2018a61c5d7880e25ac4e749968ad53513a056b9a8a4910294ed0f46'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_201101-201112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_201101-201112.nc' 'SHA256' '7af43cb68fa46b3202185ba45d783dd724f312d568036246e654a73719931e35'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_201201-201212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_201201-201212.nc' 'SHA256' '2e94e48e2fdcd1b31e50aa167521864e56cc4749120d56c0aa45f14a634dd30a'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_201301-201312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_201301-201312.nc' 'SHA256' '21b5e87b5a9232dd6e526e44eda76d1bc8ad782b2308f6af66686cd4c1c3f65b'
'hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_201401-201412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/highresSST-present/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_highresSST-present_r1i1p1f1_gr_201401-201412.nc' 'SHA256' '5885cc534fd0e50e5f5c5b4be75b1473782b70fdbc89b08e90b641d2660d5308'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if ((mVer<5)); then
        echo "Java version 1.5+ is required for retrieving the certificate." >&2
        echo "Current version seems older: $(java -version | head -n1) " >&2  
        return 1
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 65 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
