#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-index4.ceda.ac.uk - 2020/06/03 07:14:49
# Search URL: http://esgf-index4.ceda.ac.uk/esg-search/wget/?distrib=false&dataset_id=CMIP6.HighResMIP.ECMWF.ECMWF-IFS-HR.hist-1950.r1i1p1f1.Amon.hus.gr.v20170915|esgf-data3.ceda.ac.uk
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='http://esgf-index4.ceda.ac.uk/esg-search/wget/?distrib=false&dataset_id=CMIP6.HighResMIP.ECMWF.ECMWF-IFS-HR.hist-1950.r1i1p1f1.Amon.hus.gr.v20170915|esgf-data3.ceda.ac.uk'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195001-195012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195001-195012.nc' 'SHA256' 'c1a534aee04da8175237eeae061a16502e98ae19bb4b773b8e0ee2298da07261'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195101-195112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195101-195112.nc' 'SHA256' 'ffedb1b278e3d822bb9f15668a444a103c08b5829e5372215c41107b3daa3555'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195201-195212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195201-195212.nc' 'SHA256' '07dc6eeb6d3d5cfeae34fb7317cdde7a18a103d7a6d17d571f67483d12828bc1'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195301-195312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195301-195312.nc' 'SHA256' '40a842c182e80d023f25ecc55f44fd9de8811075bbc4bb2584077f803e3c8fcb'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195401-195412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195401-195412.nc' 'SHA256' '630c46c591da43e0e562e0774dba90d74347c8fbbd1a115448de1bf1072c9ae4'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195501-195512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195501-195512.nc' 'SHA256' 'ec96cacf05a5d17e49fe8f9601855132b9db3fe0228138aeb05a3dcde9345b5e'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195601-195612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195601-195612.nc' 'SHA256' 'bd9056a2cb1178999e6070bc193054802db9cf30327b7d704e5f95beadb3bd3b'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195701-195712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195701-195712.nc' 'SHA256' '94ecf9545048370f567ae7cc6d0bd99b37a20aabf1b0f41c742d24e75432f818'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195801-195812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195801-195812.nc' 'SHA256' '5a7f94d70260a7d7090127ad5dabea2f2a73febb0249b1d1f0063f93f84509e7'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195901-195912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_195901-195912.nc' 'SHA256' 'f1d49e668bb3a85003ada208678ba0dfa788c957683faf9a37d4cef4eacaf647'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196001-196012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196001-196012.nc' 'SHA256' 'b92a8ae2d9881da0f6261f123f474ee8861eefcecb443ec18d67db80af18150d'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196101-196112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196101-196112.nc' 'SHA256' '295b6e67c22ddb6970b529ae54781c7ffb2be06afea65b0720b9f10015cae64c'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196201-196212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196201-196212.nc' 'SHA256' '99508ce7dc0ef34134974e34668d0e3667496c0310ed77e46f4764a7ff16d21c'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196301-196312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196301-196312.nc' 'SHA256' 'c4440f38cdbd73b821f519988d2f4f14f67097d98aa813bb040735b6289fbe49'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196401-196412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196401-196412.nc' 'SHA256' '84e5803cb2be2ce938f7576cb4af420ae3014c9aba8c0cf07e04ee64a5ac6830'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196501-196512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196501-196512.nc' 'SHA256' '98bd3814b6ca076e4f8d5a3f63af6f0c8382e7845611da09dd4f22e188355498'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196601-196612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196601-196612.nc' 'SHA256' '5a7f9ec12de3919a11a453dde3a654efb60a40303302c74c4524ad1e37980b6b'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196701-196712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196701-196712.nc' 'SHA256' '2eb7edcd715632c305f7b031e31e9cec38bf687946066b1a78dc51be183eb6c5'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196801-196812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196801-196812.nc' 'SHA256' '4c6cdc40fbca78405dbd16843bf8505a073023b62714514a55dc17e8871660f2'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196901-196912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_196901-196912.nc' 'SHA256' '840a0613b4964a81fe8ca1f0ad29f9793bb12ee637df22b41c0a90fa48ff9ffb'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197001-197012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197001-197012.nc' 'SHA256' '20a56668ed36eaef253047d141bbf9ec25540a0ac3b4e6c09a6807a0b60b9f3f'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197101-197112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197101-197112.nc' 'SHA256' 'a4d69ffdb9ea2f79887f6389e184e498cd1e3e284e1f0e0a075e92fe2a0ea74c'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197201-197212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197201-197212.nc' 'SHA256' 'f09f25b3ec18b1de6a965449d4a3ead0d306a5828c6a4427b65271fa6d17d06e'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197301-197312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197301-197312.nc' 'SHA256' 'ce039428bd639dfa29a7af107d7e6b9ba629c13ad8ea0da58ddad4e2e721bf50'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197401-197412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197401-197412.nc' 'SHA256' 'a995e699f80dae805728619d5a10a7c10c052ee7a053791a4430523d977786ab'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197501-197512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197501-197512.nc' 'SHA256' 'f6a85cca8f72a8f1f95fae53eb148569fee1fa9e698541ec641978434f2394df'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197601-197612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197601-197612.nc' 'SHA256' 'c784a8771a189b042ef1039ac2fbf39ff139e9794b6542e8695fa75ec895f322'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197701-197712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197701-197712.nc' 'SHA256' '0186faf4e3f2d9eb96f937c3f10c67445322f063e42a23e051b4bbbe81d8478d'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197801-197812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197801-197812.nc' 'SHA256' '3299fd3273e3af55b70edd516e7306d4861220e2c42bec21a920578233b6129b'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197901-197912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_197901-197912.nc' 'SHA256' '875a3f140cbbae05c5e6f3c0dd9b66c492c105a8c26d79695a1e226e6761960e'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198001-198012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198001-198012.nc' 'SHA256' '30225dc350dd0266a569fb23017e0048bc803163918d83ae996a7ff2f9478df8'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198101-198112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198101-198112.nc' 'SHA256' 'a76dc06bcde10f30ad4e8db09e6d05ad2e2d74d8d93c605ec9962f2ac9b9b5cf'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198201-198212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198201-198212.nc' 'SHA256' '11d8734facbbd1371e5aee8571b59ddc627bc483c11a0e8631d5e80705744ef3'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198301-198312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198301-198312.nc' 'SHA256' 'dc5fb3b115d3f89656c1400937e4dd8d27df2933f184a0f5ee09dd60b2f4f01f'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198401-198412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198401-198412.nc' 'SHA256' 'd20a3e1a30fac291d3570e4b99a3d7fab4bd0f277c4c32e6db7e857050ee036c'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198501-198512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198501-198512.nc' 'SHA256' '2a5876c7a98bc92d39f47066697e94220de10e4ad8aed96fdb566b6ab0a4a5a6'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198601-198612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198601-198612.nc' 'SHA256' 'c88938c0060c10f2595594c9c3e64796ba4e362bf0fe93fb97fedb02693c423a'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198701-198712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198701-198712.nc' 'SHA256' '3de0e9d5b6070a5207d60f726bd61a44181ff158bb3459225adf7c9d7439feca'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198801-198812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198801-198812.nc' 'SHA256' '39790cdf996f28fd04a8502c4d84a5fd27970eebd381e0f2c66e0f855202b4a0'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198901-198912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_198901-198912.nc' 'SHA256' 'ce5d0397c61db9df5c9afacbc832ccb3e81ec95ca0ac4e412d65b7e3cec29580'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199001-199012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199001-199012.nc' 'SHA256' '2c727d2d5f4b8b5a15626d61f9cfe8f9b8091b69202b5666a4ff57d876fa8878'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199101-199112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199101-199112.nc' 'SHA256' 'c5669e68898a6e453d3fabdc207d7d9f77f31fae50435281ff7aaaa05c44bcd4'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199201-199212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199201-199212.nc' 'SHA256' '81b31c14002ce232e1c173e40e9bccc677127b75de1f984c21af47365a6ec4cc'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199301-199312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199301-199312.nc' 'SHA256' 'df60a751a28cde2d01e3f77a8c2c3e705bf9659283107b71f6198e79dd2ca751'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199401-199412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199401-199412.nc' 'SHA256' '7bb402dfad73d459b2cead8eb97630388db93967235a9adfe7ba63bb6cdd5f4f'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199501-199512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199501-199512.nc' 'SHA256' '47c50ba66de68831da151094e913e4102b61f91b3405a5f24f36b7b4b43a8c23'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199601-199612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199601-199612.nc' 'SHA256' '3adfa8c9bce1d516483cfb11583d465316501616a8b9f73643fea6723ec2f43c'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199701-199712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199701-199712.nc' 'SHA256' 'c63dd7d247c22da055cd81473ec44989278f87566e377b262f0a20f015a1e6dc'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199801-199812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199801-199812.nc' 'SHA256' '94f7a51eaf0dc3d0950ce883a55e1eed64cd7f4483204346b6dde5317bcaa9e5'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199901-199912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_199901-199912.nc' 'SHA256' '87a45defad2647aa865bd68c5acb917f96d03bfc6314e378ccd970625e8de01f'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200001-200012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200001-200012.nc' 'SHA256' '16851974b1606c6f45662a20eea998381c8c47455b0f19aa4099c1c45dfd0318'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200101-200112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200101-200112.nc' 'SHA256' '5ef8928a47015bb0de9e69d1147ce1ac3e89e65c6f7a64f116f777edd7f7d213'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200201-200212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200201-200212.nc' 'SHA256' 'aac33eba490bb96a1196b1f97711141fdca3c69a214e9e5cf6ba12e384ecaf57'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200301-200312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200301-200312.nc' 'SHA256' 'f3a5f992eb0cdd873166b279ab2026eca7273e910cdf5011297261e2d14e6508'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200401-200412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200401-200412.nc' 'SHA256' 'd3ed5e9efa5762800fdc44c3de7ad03df13227ffa596fe7cadc9d2eedac4018f'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200501-200512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200501-200512.nc' 'SHA256' '9ab2943d1460b37ea41f5b5368c300bb0dd09df7d49dc72aecc57490f92c402e'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200601-200612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200601-200612.nc' 'SHA256' 'ac9aa700c6919df92c825a7116591259ddf7d5312ac8d50233afc8aecbc57936'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200701-200712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200701-200712.nc' 'SHA256' '9e59d5de50fab472cc8dbbfceedcccbd0d329be02aea7aeeccce9b8bb9f5fc9c'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200801-200812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200801-200812.nc' 'SHA256' '36fea1bc3fbd38b6a9715a1450b15cba700667e850b942033ce6d0437d5a071a'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200901-200912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_200901-200912.nc' 'SHA256' '4d72b3832a8ef76afe4c0047aea4e3fc503fc50ac689fec8872d0c13eac1c576'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_201001-201012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_201001-201012.nc' 'SHA256' 'ab68f0c888d4aea2f084f5c04dd3fcfe50f46320b37eb55ff01d152159119f26'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_201101-201112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_201101-201112.nc' 'SHA256' 'c89fbf23439aa2d98c9f9315a558504fd6f2f33f45d34b54b95a04fd626464aa'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_201201-201212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_201201-201212.nc' 'SHA256' '203a8e8ad4427cf83cda90a0b1928a49a5c803b7cf537c69654b344b55ed7393'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_201301-201312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_201301-201312.nc' 'SHA256' '9485b99a0d454d8aba27fce4a4596ec5ec0f3bb6e5cce1d60aaf9afdc0c34756'
'hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_201401-201412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/ECMWF/ECMWF-IFS-HR/hist-1950/r1i1p1f1/Amon/hus/gr/v20170915/hus_Amon_ECMWF-IFS-HR_hist-1950_r1i1p1f1_gr_201401-201412.nc' 'SHA256' '7f3cd96bc825993451a906b4e9ec450d4ce0410f62b16e534d9968b1b82079c4'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if ((mVer<5)); then
        echo "Java version 1.5+ is required for retrieving the certificate." >&2
        echo "Current version seems older: $(java -version | head -n1) " >&2  
        return 1
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 65 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
