#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-index4.ceda.ac.uk - 2020/06/03 20:40:02
# Search URL: http://esgf-index4.ceda.ac.uk/esg-search/wget/?distrib=false&dataset_id=CMIP6.HighResMIP.MOHC.HadGEM3-GC31-HM.highresSST-present.r1i1p1f1.Amon.tas.gn.v20170831|esgf-data3.ceda.ac.uk
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='http://esgf-index4.ceda.ac.uk/esg-search/wget/?distrib=false&dataset_id=CMIP6.HighResMIP.MOHC.HadGEM3-GC31-HM.highresSST-present.r1i1p1f1.Amon.tas.gn.v20170831|esgf-data3.ceda.ac.uk'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_195001-195012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_195001-195012.nc' 'SHA256' '5f42d59178ca8e54fa54971cbdf24c9016082551aaea2ba4c1d99989b64c3eb2'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_195101-195112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_195101-195112.nc' 'SHA256' '00ded9e5ae9f59c379ad818a9ff0c4e575edec8160b0b07ca588c942e90f5cd5'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_195201-195212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_195201-195212.nc' 'SHA256' 'a0ba06e7aa8f2949c5b4802a4ab55b858d81b8e5537f67a171fa658f1c4af35d'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_195301-195312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_195301-195312.nc' 'SHA256' 'c358cbbc99c4a3787a739b7de6b8552e993a72522dfa7b06e5e0fb9d0666838b'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_195401-195412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_195401-195412.nc' 'SHA256' '3dbe714243c60e50b5fbc0febfaaacb3d9ed13f14ef4125023a29c237b937daf'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_195501-195512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_195501-195512.nc' 'SHA256' 'de76b4778b9aa7a5d52f32069662e4a19b99f95444f5f5a65f610465ed32103b'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_195601-195612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_195601-195612.nc' 'SHA256' 'f2751c79ce81fe8b7ef697b16687502840ac96b019fb668743e937e351111276'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_195701-195712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_195701-195712.nc' 'SHA256' '53916bb6c68876ff6420b00e3baece6072a010b8b171709f3b5566bc831d1124'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_195801-195812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_195801-195812.nc' 'SHA256' '22b57a45c19fb2eafc53bef4235d71aea527a020502b9cbac6282e82288a3709'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_195901-195912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_195901-195912.nc' 'SHA256' '23c047de34b6fd176fb7628c3624aaf793403aa611fc2b124368d31c29e7e4f7'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_196001-196012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_196001-196012.nc' 'SHA256' 'a06297aeb673d3a4a964634d666b3a94260a7febc797bf524cd52a3da3d2b6ae'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_196101-196112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_196101-196112.nc' 'SHA256' 'cc3c057d917db9e142355eb6fc97e0e9a1b05431515b72f7b382f86de095926b'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_196201-196212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_196201-196212.nc' 'SHA256' '8d01c8e6c09ba571468499d14ea9667a69f05b47bb87c8df852a44599d5b6f3b'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_196301-196312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_196301-196312.nc' 'SHA256' '68d3fa828a8478cf1f7f0ffa683094252315ad854e633dbefbeaec6d9effe0c8'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_196401-196412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_196401-196412.nc' 'SHA256' 'fce186ffce1e13b5366e54c0e889713b91db0b321487a83a7634652fad2554c9'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_196501-196512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_196501-196512.nc' 'SHA256' '48a7e42d3ce58dad40c17390fef45d94677c6409cd3dfaf47d0e94ab80057b79'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_196601-196612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_196601-196612.nc' 'SHA256' 'aa0bd4f2379a9a0b9f41daf4ca9aec3937a364350bec052fcc7a16a18175671e'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_196701-196712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_196701-196712.nc' 'SHA256' '56268db1e3b89c857641d379c8dbd35cc0bfbf755109f09bfe9381682b8f6da6'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_196801-196812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_196801-196812.nc' 'SHA256' '1fb0e5b6732b51200233d58a283ed820eed0fb6d7a8006aa83c4794f95faf7fd'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_196901-196912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_196901-196912.nc' 'SHA256' '17694c0f5cd1ec399dc721750adfdfcd750bda0eb217dd4ded0296a474d82e02'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_197001-197012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_197001-197012.nc' 'SHA256' 'def77ef3c5afffe05e9c38f27beaa1fdff6fe459fe15191509a8703cbf1d9e8f'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_197101-197112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_197101-197112.nc' 'SHA256' '476737225769b18e6f061fe44994a3871b73adf7b917729b9407de19cdb5fb27'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_197201-197212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_197201-197212.nc' 'SHA256' '27d8f5aad01361dc8d7b62fac84ee60b37a5e2103c4bd9e727ef432f5f19feb2'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_197301-197312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_197301-197312.nc' 'SHA256' '84e8a17c8d1b3cd96b8bfa9d1d68ba1d1b0d1e7677fa1deab59f8b4a8fca042f'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_197401-197412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_197401-197412.nc' 'SHA256' '4bb86cdf8227c3ef801a3cff6426d05dffffe6f09bcd14e9ec59358b747d64ad'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_197501-197512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_197501-197512.nc' 'SHA256' '73982323f11b7cd328a50db852b7de2a68b3664f9850fda6c49614f1b699eb54'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_197601-197612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_197601-197612.nc' 'SHA256' '6b56854f688fcff2058f0532927ab67c5dc5b6826b3a99ea3ddeb359a402e456'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_197701-197712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_197701-197712.nc' 'SHA256' '4f1beefa22b763735005b153ccb022117075f4b61bccac3567249cefcb50c010'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_197801-197812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_197801-197812.nc' 'SHA256' '614c5a292644deacc3ff0eb6a7d0936e7d0298cb8556fba547a31c61ec7f772d'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_197901-197912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_197901-197912.nc' 'SHA256' 'dcc4b4d4497cb017cec618194c6115a6be26e15e7aaaeb64843403458ba137b8'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_198001-198012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_198001-198012.nc' 'SHA256' 'e0e8ba98656ac79917438dce2e328df9512828d4e88d5293aefa5312e6a0a8e6'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_198101-198112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_198101-198112.nc' 'SHA256' 'd6e1c80d64e0bb4093ebff308f6419101a6da760aad643493f01cb630cdd02f9'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_198201-198212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_198201-198212.nc' 'SHA256' '9f3f3fd65207e3a34b5a16ab91ab586858e0cd5bdda5c9afa282c93b5f5dfabd'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_198301-198312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_198301-198312.nc' 'SHA256' '54c4c93ab3f20d4977de06fa55164e4095d19c2005805521623b9037b507cffd'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_198401-198412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_198401-198412.nc' 'SHA256' '0169e78a31519000f1ca27ccf3f1d7ab570bc2512e79f78892631d4b47114308'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_198501-198512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_198501-198512.nc' 'SHA256' 'cc7c433afb15950e92c2b99ab421f221a6281fbbe4393be70335d4b054d820f0'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_198601-198612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_198601-198612.nc' 'SHA256' '62a3caf140dcc311a903dae78f9f428b25ca4e1f63265596efd73047a7283eb2'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_198701-198712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_198701-198712.nc' 'SHA256' '4e1cfe9bdd15852401ee7685f04de966d99ff5480c784268b6469406588f77d4'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_198801-198812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_198801-198812.nc' 'SHA256' 'a4d2481938458fe831beff1ce3d284d23c3a94fcb285db6c7cb6ebc356aa08a2'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_198901-198912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_198901-198912.nc' 'SHA256' '19b61c1a7fcb1c62988fa2be055c5b12e014e4bada455078623d81a62c4e7eab'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_199001-199012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_199001-199012.nc' 'SHA256' '06b3788968c2966cf0d91328ffcdc9ee3d93b25f187003aeac05f3d30a91d62e'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_199101-199112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_199101-199112.nc' 'SHA256' 'b22d04f4b7b0bd0079973a761afe3c8f99b1aef049750520e4f8d6accc69ca08'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_199201-199212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_199201-199212.nc' 'SHA256' 'bee6cd931c53481db51e7e026288b185bb08606b38a112fa0a51359e91c71cab'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_199301-199312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_199301-199312.nc' 'SHA256' '5469080fe6b4a87a14bf24e769c7e7f2888d4713ae4e97b69e523ad44a462860'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_199401-199412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_199401-199412.nc' 'SHA256' '6e4b4c7d83455a61c748473ad6da6694bd868f9724c4dc1d3d65a576335b0963'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_199501-199512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_199501-199512.nc' 'SHA256' '2933f9dac0fc9b96b7433c38df0c96415cc534f9340c4a40c1bb44d70c76c27c'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_199601-199612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_199601-199612.nc' 'SHA256' '20a930cf5264179126d21addb7664d364860c34dcd866e95f76e281282d0d38b'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_199701-199712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_199701-199712.nc' 'SHA256' '101e8c2617f1c2dc587f0e31cd4249f75dffb397feb55e961cc37af6324ca9a8'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_199801-199812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_199801-199812.nc' 'SHA256' '3ceaf932b5b97647fd956b9a6feaa5ea72a4e696c2e8e89f512dccab7574135e'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_199901-199912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_199901-199912.nc' 'SHA256' '1984bfff1ff11a7f8115f74691270e0920e53e78db53797756360aa4fba102c9'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_200001-200012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_200001-200012.nc' 'SHA256' '37a27d805b1e33f72f78683198f60acfcbf8a56d14ff5556b9440ed5023be8c4'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_200101-200112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_200101-200112.nc' 'SHA256' '87ddea31553a0128f2c9665fdbcb7973d3d7333bfef9aacf0c1e026eedcee86a'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_200201-200212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_200201-200212.nc' 'SHA256' 'ae9cb16152457daffbe3e4f46eedaf650a38653add09f6b201cc52ed0a6b2cbb'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_200301-200312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_200301-200312.nc' 'SHA256' '2eec885601d3d1db9aa85805de452956481e86c04f506e44a1f4cdd9b8710ad7'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_200401-200412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_200401-200412.nc' 'SHA256' '83964c2c7e31452ea865687b54efaadd19242a06c54e45c1063c63c9f0dd1119'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_200501-200512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_200501-200512.nc' 'SHA256' 'ca02df5e91657b6380cfb2c31cc41a0ef3af698afd4ce082cdd1ba7622b00a77'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_200601-200612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_200601-200612.nc' 'SHA256' 'cc580abcd950044c80b6bf118289d729ef48ddbd8615c08f02be8a3d866a5392'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_200701-200712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_200701-200712.nc' 'SHA256' '613a375ee5b17dfa082ed8398334261a4795d2fd3c57e40d08d173fc11be24fb'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_200801-200812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_200801-200812.nc' 'SHA256' 'b6622714dc98cabec0ca37a67017c91c89d200867c47d75d25c67934a8ba6b3e'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_200901-200912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_200901-200912.nc' 'SHA256' 'a5b4b1bbcf93f400c82dad34d02903c3c1bc9f4941630957e34fad947c9db44f'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_201001-201012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_201001-201012.nc' 'SHA256' '4ba7cdb4f38042216f1cb03a7ae4d5dade5e30f9b94b3275b5c2b81a55b2939b'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_201101-201112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_201101-201112.nc' 'SHA256' '76292f551932b5c84f9bd7d1dfabc4552abb699d4ec32ed62925e2534e19317a'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_201201-201212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_201201-201212.nc' 'SHA256' '2d1fa08f72c07089df29a36b31303ffcbad3427a0a2131fa3ab32f72852dbf30'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_201301-201312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_201301-201312.nc' 'SHA256' '8f51485c46342b4292ff7dd5b20876313e96face44fecd0946feb393a209f5f4'
'tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_201401-201412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i1p1f1/Amon/tas/gn/v20170831/tas_Amon_HadGEM3-GC31-HM_highresSST-present_r1i1p1f1_gn_201401-201412.nc' 'SHA256' '8f8e6f90fdc0846e8bb45bd1bb5cb5cd6b71241081164df6310fb6e2ade9b21d'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if ((mVer<5)); then
        echo "Java version 1.5+ is required for retrieving the certificate." >&2
        echo "Current version seems older: $(java -version | head -n1) " >&2  
        return 1
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 65 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
