#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-index4.ceda.ac.uk - 2020/10/23 08:37:28
# Search URL: https://esgf-index4.ceda.ac.uk/esg-search/wget/?distrib=false&dataset_id=CMIP6.HighResMIP.MOHC.HadGEM3-GC31-HM.hist-1950.r1i1p1f1.Amon.zg.gn.v20180730|esgf-data3.ceda.ac.uk
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esgf-index4.ceda.ac.uk/esg-search/wget/?distrib=false&dataset_id=CMIP6.HighResMIP.MOHC.HadGEM3-GC31-HM.hist-1950.r1i1p1f1.Amon.zg.gn.v20180730|esgf-data3.ceda.ac.uk'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_195001-195012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_195001-195012.nc' 'SHA256' '44a3b527fdf55f011f3de55593b655f6280af5736622670d756bd738b8089b9a'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_195101-195112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_195101-195112.nc' 'SHA256' 'f1967a73bb1e81dd21bd1849c0516d35bfba557d26d05d476a7c3466628ddc7a'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_195201-195212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_195201-195212.nc' 'SHA256' 'b4884c453d1b8a62e2e2ad69cb483cf5ffdf57bacc6b4eaf55da910e1edd610c'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_195301-195312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_195301-195312.nc' 'SHA256' '06176dacd78343cadb222af19560929f3f0c9364fd8ce9b400ddda98d974597d'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_195401-195412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_195401-195412.nc' 'SHA256' 'bf62c2046432d99a8975741411e52dbd08b6c7d75bbf99f2caebfbfb127afe15'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_195501-195512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_195501-195512.nc' 'SHA256' '08a185277e409bef51332ae7b22435f7ada3d90174eeb78307f5f2ee89d8a5fb'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_195601-195612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_195601-195612.nc' 'SHA256' 'f180bd049c70a59e9a7f8f9211f8d9e8d4f79aa08aa2ea5a6b0cb53cf1a8432d'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_195701-195712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_195701-195712.nc' 'SHA256' 'b13f8dd77d3626eb78070055c61a25ee2ca1042d5662fade61a8bfc8ca747a32'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_195801-195812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_195801-195812.nc' 'SHA256' '1cb95d8703ecdf21fc6895a6c1ad03f75a5018849e20f4ecdcefbecbda6d9d4f'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_195901-195912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_195901-195912.nc' 'SHA256' '3787bf7f5efcf1da74ec7f6349b05307fa45ac2a21ae191f6684200cc7acccd7'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_196001-196012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_196001-196012.nc' 'SHA256' '70499457fab0dad7d09fb1fba2b31d59e032e12fd5ebbefe1e5f6b795a80d10d'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_196101-196112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_196101-196112.nc' 'SHA256' '4e21bd33085ffc567183723ae8ed49c664fe785efd3250ad302ee88a92141ef7'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_196201-196212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_196201-196212.nc' 'SHA256' '6850840be15d125aa66b806ff4f50cc60b403df2d0635090ff8a9be246702b13'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_196301-196312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_196301-196312.nc' 'SHA256' 'eaa33c85fc8ed557d4cc882303a265ec052d9f864a54cea2defd5e65e5efb994'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_196401-196412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_196401-196412.nc' 'SHA256' 'ea5b1af2555b2b79f04bd84fecf47fce8e7277feaed41a1850961cf78e61f6e6'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_196501-196512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_196501-196512.nc' 'SHA256' '8401021f872e401e70811a67f3c1904ca707f0ef3c3a55abe538ab0362d25a6a'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_196601-196612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_196601-196612.nc' 'SHA256' '48def76a8705715129190dca12d17488637e3b012c2d50498afa8503fcd4d54a'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_196701-196712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_196701-196712.nc' 'SHA256' '0922a5fb121b6c32149377dc862ce0acda2098088c6f0833a010960276b349d7'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_196801-196812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_196801-196812.nc' 'SHA256' '99bf22943bf9defbe4f77c05da0b280a21d58a260b4a6e4cd1a3850eb4edf3dd'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_196901-196912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_196901-196912.nc' 'SHA256' '72e4a5ea0c4d6ef72593cd4dfdb2c7c3ba0a95cb79bd60ceb03f27adb75411e5'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_197001-197012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_197001-197012.nc' 'SHA256' '2d6f1ae4b82c1e1470ef05abed7be21e616827ddf1fdee683ab3ae9cc7b6eb70'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_197101-197112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_197101-197112.nc' 'SHA256' 'b661aa479bf1adb1536ef3f2b0bc05c63dd5e2e6829296b1cb83195b89da5d43'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_197201-197212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_197201-197212.nc' 'SHA256' '617beb9230e1eb3292283f09c99d55eb68ef430e426031fe18dd3e9f51630c6e'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_197301-197312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_197301-197312.nc' 'SHA256' '118df7da5faf933f7ad86156a4cf63c7d8ade7ef12ad41719b8ec599044a6339'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_197401-197412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_197401-197412.nc' 'SHA256' 'c35db9969d892269d8a935816c77bc2af59f60e21191e7f0e67fd3b24ca797d4'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_197501-197512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_197501-197512.nc' 'SHA256' 'f7420cd44efaa41d61c32c2f6fdebc2259bae9b798766fd0a563fb4d365db37e'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_197601-197612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_197601-197612.nc' 'SHA256' '0744065a6de5345a9b2ac6b39190ff7c1a330462de1930f7c6d664335290e750'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_197701-197712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_197701-197712.nc' 'SHA256' 'e742833798546c9657e41ebd8519fff4c5e6d9175257ca1b425d7a7cb7f6e7e2'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_197801-197812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_197801-197812.nc' 'SHA256' '04740034e94e98fb84529bf18983848d9d773ddae93714ed4c8e3539dc26925a'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_197901-197912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_197901-197912.nc' 'SHA256' 'dc0ae3ff0082cd9de1d5427257720837c354705a37934842b6e86a58d9bbfeb6'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_198001-198012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_198001-198012.nc' 'SHA256' 'b309f49625f11107f2614ed16bf64e21eca1f25a4131ae5aec015dd0c855ee52'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_198101-198112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_198101-198112.nc' 'SHA256' 'eb12e7dbc7ba3103dc293f5a91fa9ddcab65d6f5dc973ae2b7ac1a861a249aa9'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_198201-198212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_198201-198212.nc' 'SHA256' 'ed8b34e083495670a00146bf0843feb418dbf1343a6f709a1d8c48e49ee511f3'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_198301-198312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_198301-198312.nc' 'SHA256' '5c3598c86e2ec6fc6529cbaaebd56e151cb24665044929187f82c2a2e57bfdc5'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_198401-198412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_198401-198412.nc' 'SHA256' '6eb96a976da78c7fc8d7ce4e901d5238819a33acadb67553fba89e1202c35191'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_198501-198512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_198501-198512.nc' 'SHA256' '095a0b612e572d548a0dbd6693eef17d28c4874fbb269534738b6171598e0d5e'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_198601-198612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_198601-198612.nc' 'SHA256' '0710f3b4dd0de4c2d9350f496d2513dfb0eb2eb33599c1d971af654f70b34b0f'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_198701-198712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_198701-198712.nc' 'SHA256' '2e9e6f99037d12b867cf97c2256b8d931b32960c5ee1941ada8fead19d106e4f'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_198801-198812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_198801-198812.nc' 'SHA256' 'c50a3a9fd1b4103743d9fbb72891af2ae40a27c9daa4fbf9fe2a191da92701b5'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_198901-198912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_198901-198912.nc' 'SHA256' '0d656bc0945a275fab216b7d578d4b429fd265a5dbe0514605f777d0cdad77f0'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_199001-199012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_199001-199012.nc' 'SHA256' '5887326bdfc6956585a40e874c58b2383f87f644c000f68e69447ee6ef8fe94f'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_199101-199112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_199101-199112.nc' 'SHA256' '7dcf33eae4221f7b81e308622533b44ae24e941a59086c9357f9ee2775738fff'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_199201-199212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_199201-199212.nc' 'SHA256' '2ce13cea0c8f6de99979624495a31bbd911bfb5edd941dbaaec501aaf3a6b190'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_199301-199312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_199301-199312.nc' 'SHA256' '9fd151ac2fd2678254531b770ae016d3e04da8033ed8317b9f2ecce5e8c5a435'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_199401-199412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_199401-199412.nc' 'SHA256' '15fe1c7f5413cd3bc02bec4c1f626961f46f1a8870d9dee8409655a8bac66a2e'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_199501-199512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_199501-199512.nc' 'SHA256' '30bd67d25bde76911b92fed68c97982e60ef62d20d174769d9e36ebfcbb4262f'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_199601-199612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_199601-199612.nc' 'SHA256' '1a3534f4c4c8a8bdfed66f964f99a9ce523c4f099f24ba14b2ea0b158c275bbf'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_199701-199712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_199701-199712.nc' 'SHA256' '5911e452890979ac9e06218534f1dd93a06fc427ccef96f12933c0a3846aea1c'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_199801-199812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_199801-199812.nc' 'SHA256' '0f26596fd82c4ecbc0b57b184692c94f2ceade8e78f41624bb898c4665a07a6f'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_199901-199912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_199901-199912.nc' 'SHA256' '6521ee0fba5651bd87f99973594fbbdbea357e5bc1c8e548320966a7cdac4fae'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_200001-200012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_200001-200012.nc' 'SHA256' '3cc786c67d32b0b90bab8609851a5c180dc405a248af2b1fcba3f9dfed099f5d'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_200101-200112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_200101-200112.nc' 'SHA256' 'aeed9d29e6422ff24d7dc9f4973e1082ddaedc6c4d760f3ba754f867c1bfcbdc'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_200201-200212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_200201-200212.nc' 'SHA256' 'ad55d3f7a2fc5be65842299b2cc35d11206418b6dfbf74e40bb27ec272a4bbd3'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_200301-200312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_200301-200312.nc' 'SHA256' '27ce7b64214a5f0794e11a4ff9188cc2a085c3c6cd89bfa08f8b780c9bd4ba64'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_200401-200412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_200401-200412.nc' 'SHA256' '78fd866e1f23ac202a724decf367d6c48e86b8499a58961d8eac34731ce975cf'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_200501-200512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_200501-200512.nc' 'SHA256' '9aca97e3832baddcecc979cc2e29a961e41b1ee69b0eb28dc71c87c6c072e509'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_200601-200612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_200601-200612.nc' 'SHA256' 'd3c3d59c4cba383e269711eb609d4707de098d0adcfe2011f59ddedafcb9ad40'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_200701-200712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_200701-200712.nc' 'SHA256' '426f103f8c4087ee933b07e9fd6232f2570db12b2a6daf0eb5a767b9bfc42261'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_200801-200812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_200801-200812.nc' 'SHA256' 'd6516fd0f2c96c4d0e52e135f3c4cf39e51d02770a5fc3f93d5bf8aced55e162'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_200901-200912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_200901-200912.nc' 'SHA256' '34fdbbc000b09996c3ec6f5c49ce9bf71add3a566d3793fec06fa60e402cdc4f'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_201001-201012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_201001-201012.nc' 'SHA256' '3d39f9f33f9b516b84445eba2786ed0c32a61915e561153d2847d0ca55e7505d'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_201101-201112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_201101-201112.nc' 'SHA256' '42db41a3c597e698b414585f6daec2cbe4e6749a8c9a6160a27149ea4e4f0945'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_201201-201212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_201201-201212.nc' 'SHA256' '75a8bbde8b4c2b56a1b8063e49e429f551c340711380f07c6288234b1d69f6fc'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_201301-201312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_201301-201312.nc' 'SHA256' '9870926d86e9897844a4b4dc34e009cf8ff2fb6484cf7a1c9880e74c7197fa00'
'zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_201401-201412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/hist-1950/r1i1p1f1/Amon/zg/gn/v20180730/zg_Amon_HadGEM3-GC31-HM_hist-1950_r1i1p1f1_gn_201401-201412.nc' 'SHA256' '6f85e2ec12b09656e52150462b2b56d5a64fa7cb01fdc8ec0ff0af3bdde11c5e'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 65 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
