#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-index4.ceda.ac.uk - 2020/10/23 07:54:09
# Search URL: https://esgf-index4.ceda.ac.uk/esg-search/wget/?distrib=false&dataset_id=CMIP6.HighResMIP.MPI-M.MPI-ESM1-2-XR.hist-1950.r1i1p1f1.Amon.va.gn.v20180606|esgf-data3.ceda.ac.uk
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esgf-index4.ceda.ac.uk/esg-search/wget/?distrib=false&dataset_id=CMIP6.HighResMIP.MPI-M.MPI-ESM1-2-XR.hist-1950.r1i1p1f1.Amon.va.gn.v20180606|esgf-data3.ceda.ac.uk'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_195001-195012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_195001-195012.nc' 'SHA256' '5bdd6bde3a0b927a07755cb8cf4f2141af42f956c1138c8f59e68c25e784cbef'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_195101-195112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_195101-195112.nc' 'SHA256' '02d3cc456a1bdf59b9130e90109cc200a78990b847826feea32e09e9d00a934f'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_195201-195212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_195201-195212.nc' 'SHA256' 'dc0a5727258483c2454d4eb5453e1511e25d50b50e25a374a57a150a21d2d547'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_195301-195312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_195301-195312.nc' 'SHA256' 'd203382c892af1c2ae9a162da586bce06b22ba3218d24cef1409c2172130903f'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_195401-195412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_195401-195412.nc' 'SHA256' '445c0e84ddebc3bb27714d5dc802d68110f0796414c78a7b401741ad739ab7dc'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_195501-195512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_195501-195512.nc' 'SHA256' '8e3e046014ee6958f3fa084b8a4ce8069a26d1cb6eecb8b887ca06d5eff6e3d2'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_195601-195612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_195601-195612.nc' 'SHA256' '2eb79bf9817a258a2eceff58124b9d75c8ffd07685a83b8bab05777843c1e422'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_195701-195712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_195701-195712.nc' 'SHA256' '632de1426b609bdb0501e4d607a0b6d9e9bd3a5ecd126d92e516e735f0daca86'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_195801-195812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_195801-195812.nc' 'SHA256' '973877065f699965955fbe331a32570591293e1ce01d29a6e6581f48c803f980'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_195901-195912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_195901-195912.nc' 'SHA256' 'eae7a6433a4f4418cdad4b3ae9a0429c6a81a42381b829a265f7d1a0376d1a10'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_196001-196012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_196001-196012.nc' 'SHA256' '2d3bc1cba6a348e595e0ab2077c5d2f0756f5349a810fa49b5a14746abcd2bb9'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_196101-196112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_196101-196112.nc' 'SHA256' '63e53b6c301a565949cea64b751bb1c2d4a3f37f1aa2ccf42dcfe7a648a05ed0'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_196201-196212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_196201-196212.nc' 'SHA256' 'd7e22f257d9418a10e0e6b29fac09bfd2292b8063d7e8ef4b24de01e8f7d7ec4'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_196301-196312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_196301-196312.nc' 'SHA256' 'c6a1ce673a17a0d05cdefacc0d51d87433e3154aebf18e872c7bfadf7d340c7a'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_196401-196412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_196401-196412.nc' 'SHA256' '86bebbcbe417ad2f9fb402f71ce169468d5eb425b245cfa42f2aa595f737f683'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_196501-196512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_196501-196512.nc' 'SHA256' '2069394e1f17fc0b0785f6e26d650491c793b2e5d5fbc2e93e2e2e17264e5da6'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_196601-196612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_196601-196612.nc' 'SHA256' '06b21731f3e5362c265d1e7ac72a6f8a44c88d83a49d21664cf941df9550cee5'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_196701-196712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_196701-196712.nc' 'SHA256' 'c61b89bb02f9d405da0c3608ef5dd203bd224ccb9060059d3954a7f86c0d2a4e'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_196801-196812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_196801-196812.nc' 'SHA256' '1c284416b7a810ea92304b15e80c85e21d0370561c7526e3140c0a146b38a4ca'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_196901-196912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_196901-196912.nc' 'SHA256' 'ef808b70d0bec42eea164c9ab0c81c479d4133bf810787aa78304525bbb5a23a'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_197001-197012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_197001-197012.nc' 'SHA256' '0d86483374115674fdb1d5b9109f88782d76684fbbc4e1fb0f8fdac4d114880a'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_197101-197112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_197101-197112.nc' 'SHA256' 'd2dd11dbefbb2772948595288a71dc2c8a03525b97eaeb41603ec69bf76a44fc'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_197201-197212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_197201-197212.nc' 'SHA256' '725bf44d80ed70439f29c60ac7b3ddd49f32232b9cbb6a14f10f1147126c5e81'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_197301-197312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_197301-197312.nc' 'SHA256' 'b88bf5fc48da6f6ea6928da7ab24cad59ab90a3e2645d1d6a334af32555adfb2'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_197401-197412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_197401-197412.nc' 'SHA256' '2a55ec415c33b5f204b84e8ba34cbc6a36c21f772546adc3204ff3a686392b97'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_197501-197512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_197501-197512.nc' 'SHA256' '545bbc9b98ac939a5bae4e55ef0532e527c78951b6f29d97ecb654b1a49c20b6'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_197601-197612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_197601-197612.nc' 'SHA256' 'd3608dd794c83853f4878192d13a6aa4f5c8a376d3b23105ac7feed91e6453fa'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_197701-197712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_197701-197712.nc' 'SHA256' 'c1e60a53a3bef936729228b44088d544106167b8c6d2c11b3929b66af7763495'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_197801-197812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_197801-197812.nc' 'SHA256' '210338d16dcdd2b3f1eaca7f19a7aba08902d41b2a02d7eaa2611c98b556d206'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_197901-197912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_197901-197912.nc' 'SHA256' '2d4bf85cdba321e876e38e9bb53f12a77be85c6fecb4008988b5534bdaeb2553'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_198001-198012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_198001-198012.nc' 'SHA256' 'dabd33cb7454e057a5de0268d5bfbda753bb85948accfe6ca8bbf5140b6b5171'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_198101-198112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_198101-198112.nc' 'SHA256' '7ea9a665152b7c26dad314e765631856f72d44133cc3c396f0f8bec2faf3dba3'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_198201-198212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_198201-198212.nc' 'SHA256' '288ced84c180e35d2e2a0902b1367f8b4fa688f4dbd39d38464cd0e90225b57c'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_198301-198312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_198301-198312.nc' 'SHA256' 'dd9bd477a7d0ce39c2dc8331a620872e8268e2a1e281480f4333f491feca3e23'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_198401-198412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_198401-198412.nc' 'SHA256' 'f51b959dd531dd6d6de7bd77df9ff875a3137722322668f89c9c2ca0206d5ec1'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_198501-198512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_198501-198512.nc' 'SHA256' '19a6812833bc7ca19d7d2a7b15377d9d08bab51823103303416fe121496fd3eb'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_198601-198612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_198601-198612.nc' 'SHA256' '3fc41004703873b14d8070e00890d6fd50ecc6464384b74e31ffc9dc1b83bfb0'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_198701-198712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_198701-198712.nc' 'SHA256' '449d6d31bf2d89c0f00d52a3f37c989b4e567bf74b8ea3687294bf3bbd3b4b73'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_198801-198812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_198801-198812.nc' 'SHA256' '797b90e659809cb2f32befa08a4c21c7b2174e2023212387d5c40a0084b6f988'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_198901-198912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_198901-198912.nc' 'SHA256' 'c77f7f07e31805bc17dec0195cd85cf9f0882357f980b994d74d2e0942ee1132'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_199001-199012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_199001-199012.nc' 'SHA256' '54f29c1bf3a1ddd60542f93b998c95b04ecec03004b71a5820334867abca773b'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_199101-199112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_199101-199112.nc' 'SHA256' '1a52a9767df080e75234733e79d30251f70e9a0e456ae115cf9daaa0ba8bdfe2'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_199201-199212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_199201-199212.nc' 'SHA256' '86fd764f26798673968b17f7c616d658a4e1121a29ac4b0ed5cf4671460b673c'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_199301-199312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_199301-199312.nc' 'SHA256' '15dee286963996544322faa113404bc360c21832827254fef9e76deb0de80bcc'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_199401-199412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_199401-199412.nc' 'SHA256' '7008c7658bcc6a60f1d15e4799208c4e71fc993124640e5e9e067af67dd4a142'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_199501-199512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_199501-199512.nc' 'SHA256' '7f680bea7493fae3f1711263d832f0daa7c06b787436e869de5a03c92989ad70'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_199601-199612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_199601-199612.nc' 'SHA256' '96e3f146d33114c5bf8b2bd5677b0b32098ff3fc39a97ac1c81e1bedc3ff6c30'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_199701-199712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_199701-199712.nc' 'SHA256' '114e8ed223cec756b053d9497b3506b92849a13dd64377cda68c80b5314db3e1'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_199801-199812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_199801-199812.nc' 'SHA256' 'c7cacb61a07dfdff752c2bcc4ce51692b30226cd7949a8e6219e584b2a375964'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_199901-199912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_199901-199912.nc' 'SHA256' '9178e7ac1e9bf85027b68a139aeafd5580c620ccfcd012ea14724dcdf0e8354d'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_200001-200012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_200001-200012.nc' 'SHA256' '2c385cf5051ea2cae7756ae794805af1e32d5f1647942260a6574f6f349a6390'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_200101-200112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_200101-200112.nc' 'SHA256' '488079002270f2891ece927485b4e6ed1aa39e3f4ad129e570aa9928b6b80f79'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_200201-200212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_200201-200212.nc' 'SHA256' 'a7d53e3a980036cd2a10ad9da216051337475e0da3f17544286fdcb5f3498f02'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_200301-200312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_200301-200312.nc' 'SHA256' '3d713dbb1e235bb4ce28cb6c8b15b1588ac06bd327571a544aabded7b4fc0a46'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_200401-200412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_200401-200412.nc' 'SHA256' '91bc24ea2240133a0dcdb44b0528f1de81adac30635c8eb769655291fd49f09a'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_200501-200512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_200501-200512.nc' 'SHA256' 'dd7ed9019eba94f7cea34b4ffbcb4585aae57da985daefaa9b733d5c2036e717'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_200601-200612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_200601-200612.nc' 'SHA256' '4a2db4ab4b9d518ba9b560c4da57a8322250f866d8299326dac5b254dfab8135'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_200701-200712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_200701-200712.nc' 'SHA256' '44435b78b90d5f9bfb4bfeaa8a152c0b0312ede973273d1d873a56edc2d73a9b'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_200801-200812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_200801-200812.nc' 'SHA256' '9bfe7412e3b0bba2254b5044db56d94ff3f7cc8187b449444738b49633e738f8'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_200901-200912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_200901-200912.nc' 'SHA256' '4d5b1655c0a75b6f68e6f258ad104a7872c7a7705a4d345ac836740aac1032a1'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_201001-201012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_201001-201012.nc' 'SHA256' '50a63fdb01c20767200050ece4dc08bb007afe398bed926ba33d4a2c35dd856e'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_201101-201112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_201101-201112.nc' 'SHA256' '67ab35fb4f1b719e030e8458c1866bad33880803539b6ac59b0c8fe1000e0e12'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_201201-201212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_201201-201212.nc' 'SHA256' '9db52cbc6f9e562fe3e1046c38b033c09d95e67709a70831c19b1611ab51ef6a'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_201301-201312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_201301-201312.nc' 'SHA256' '7d5eaa658bb654c9188691df651d9aadf2065fdb663754da369fde5ea802a0a6'
'va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_201401-201412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/MPI-M/MPI-ESM1-2-XR/hist-1950/r1i1p1f1/Amon/va/gn/v20180606/va_Amon_MPI-ESM1-2-XR_hist-1950_r1i1p1f1_gn_201401-201412.nc' 'SHA256' 'b1c4b62ff9d3ed559c6947a89e6e238db92be9968af3b1bcf6b3df906483f14e'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 65 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
